name: Kotlin hw 5 check

on:
    pull_request:
        types:
        - opened
        - synchronize

jobs:
  test_linux:
    runs-on: [self-hosted, kotlin]
    timeout-minutes: 15
    steps:
    - name: Setup Chrome Deps
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates libnss3 libatk1.0-0 \
        fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
          libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 \
          libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
          libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: '125'
    - name: Check Chrome version
      run: |
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        generate-job-summary: true

    - name: Assemble and test with Gradle
      env:
        CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
      run: |
        echo "::add-matcher::.github/problem-matchers.json"
        ./gradlew build
        echo "::remove-matcher owner=ktlint"
    - name: Upload check reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: build/reports/
        retention-days: 1

  test_windows:
    runs-on: [self-hosted, kotlin-win]
    needs: [test_linux]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Assemble with Gradle
      env:
        CHROME_BIN: C:\soft\chrome-win64\chrome.exe
      run: .\gradlew.bat assemble
    - name: Warm up js browser
      shell: cmd
      env:
        CHROME_BIN: C:\soft\chrome-win64\chrome.exe
      run: gradlew.bat jsBrowserTest || exit 0
    - name: Test with Gradle
      env:
        CHROME_BIN: C:\soft\chrome-win64\chrome.exe
      run: .\gradlew.bat check
    - name: Upload check reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports-win
        path: build/reports/
        retention-days: 1
