name: Kotlin hw 1.2 check

on:
    pull_request:
        types:
        - opened
        - synchronize

jobs:
    build:
        runs-on: [self-hosted, kotlin]
        timeout-minutes: 5
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: 21
              distribution: adopt
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 8.5
            generate-job-summary: false
        - name: Check list of changed files (should be Task.kt only)
          run: |
            git fetch origin main > /dev/null 2>&1
            if [ $(git diff origin/main HEAD --name-only | grep -v ".kt" | wc -c) -gt 1 ];
              then echo "Your solution changed not only Task.kt files. Please roll back changes in other files" && exit 1;
            fi
          shell: bash
        - name: Build with Gradle
          run: |
            echo "::add-matcher::.github/problem-matchers.json"
            ./gradlew build
            echo "::remove-matcher owner=ktlint"
